### ISSUE TITLE
Similarities with knockd

### ISSUE THREAD

**Issue by dandanio** [prashantgupta24/firewalld-rest#9]
So it is quite similar to knockd, if less secure?

**Comment by prashantgupta24** [comment]
This idea was inspired by knockd, it is similar to knockd using REST with JWT for "knocking".

**Comment by CompuRoot** [comment]
Don't get me wrong, but bringing a lot of dependencies to do a simplest task that can be done in 20 lines of bash script with zero dependencies. Just google for URL knocking. The first I found: [URL knocking](https://superuser.com/questions/1176359/what-is-difference-between-port-knocking-and-url-knocking)

Would you want URL/REST link protected? Simplest basic http authentication that runs over https will do the same as 'bearer', add fail2ban that watch for failed authentications and it will be rock solid protection. You can implement asymmetric cryptography to rise protection even more, but it all can be done with tools already existing in any nix systems. 

IMHO - no need to buy a commercial truck to care a single nail. Than more dependencies, than more possibilities to brake - old plain KISS principle. 
Spin out kubernetes with Node to just implement JWT ?
openssl+bash+jq is all what one need to implement JWT.
It's all new cool features you using, but count  the cost and complexity of your solution.
Count the cost of supporting your solution over time and compare it with simple URL knocking...
I'm sorry if I miss something, but it looks to me as when microscope used as a hammer for nailing.

**Comment by prashantgupta24** [comment]
My contribution through this repo was never to provide a "microscope" or a "hammer", it was to open source an idea. You can take my idea and convert it to a hammer, a microscope, or a commercial truck for that matter. I will be glad that my idea helped in creating that, and you will be glad that you were given the idea in the first place.

If you think this idea has a potential to be something better, I would request you give me a list of actionable items that can be implemented to use my idea in a better way.

**Comment by dandanio** [comment]
@prashantgupta24 I hope someone finds it useful!
